<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Security\TokenAuthenticator' shared service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Security\\TokenAuthenticator'] = new \PrestaShop\PrestaShop\Core\Security\TokenAuthenticator(new \PrestaShopBundle\Security\OAuth2\ResourceServer(new \League\OAuth2\Server\ResourceServer(($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] ?? ($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] = new \PrestaShopBundle\Security\OAuth2\Repository\AccessTokenRepository())), new \League\OAuth2\Server\CryptKey('-----BEGIN PUBLIC KEY-----'."\n".'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAy2OnQYwtyd7O8RxzyRWm'."\n".'FE2n82yOK9uYl01eshxFyNZ9XONsdIflXQoOTW3HWFKJdipmZIq1i1UUdkeWEvkZ'."\n".'r4M6Olf3ey+s+rjdMUZjLlJkUCLEt6KYRJ6CX1mPMbpiS1UGEMGP7EX/5TuIsofL'."\n".'GbFjYT1ZvdF26vJDkw9L4ITKQBBgvwxJqI6zSNp2BBB/HoM8h1CgNiarQwzGPBZe'."\n".'AsnDKtRLP26I5Mi4gCBjVKhzWPW+l3GXXajxCQ1zr4811+8MwS/LA2e71ugyUs3m'."\n".'bUGZrM5Bss2WNY7wfZk4K+SmYOvqiiAbU1Y7umPney2ij+YeIk9n90QLEmLHxzrW'."\n".'zQIDAQAB'."\n".'-----END PUBLIC KEY-----'."\n".'')), ($this->privates['security.user.provider.concrete.oauth2'] ?? ($this->privates['security.user.provider.concrete.oauth2'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([])))), ($this->privates['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] ?? $this->load('getPsrHttpFactoryService.php')));
