<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCAj3Qrx\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCAj3Qrx/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCAj3Qrx.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCAj3Qrx\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerCAj3Qrx\appAppKernelDevDebugContainer([
    'container.build_hash' => 'CAj3Qrx',
    'container.build_id' => 'afc7d00d',
    'container.build_time' => 1747938054,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCAj3Qrx');
